name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: LeLuxNet/GitPullApi-GitHub-Action@v1
      with:
        repository: logogenerator
        token: ${{ secrets.Token }}
